<?php

$DIRECTION = Array();
$DIRECTION[2] = 'WESTBOUND';
$DIRECTION[1] = 'EASTBOUND';

$LINE = Array();
$LINE['RD'] = 'RED';
$LINE['BL'] = 'BLUE';
$LINE['YL'] = 'YELLOW';
$LINE['OR'] = 'ORANGE';
$LINE['GR'] = 'GREEN';
$LINE['SV'] = 'SILVER';
$LINE['NO'] = 'OUT OF SERVICE';
$LINE[''] = 'OUT OF SERVICE';

$LINEBGCOLORS = Array();
$LINEBGCOLORS['RD'] = 'BF0D3E';
$LINEBGCOLORS['BL'] = '009CDE';
$LINEBGCOLORS['YL'] = 'FFD100';
$LINEBGCOLORS['OR'] = 'ED8B00';
$LINEBGCOLORS['GR'] = '00B140';
$LINEBGCOLORS['SV'] = '919D9D';
$LINEBGCOLORS['NO'] = '000000';
$LINEBGCOLORS[''] = '000000';

$LINETXCOLORS = Array();
$LINETXCOLORS['RD'] = 'FFFFFF';
$LINETXCOLORS['BL'] = 'FFFFFF';
$LINETXCOLORS['YL'] = '000000';
$LINETXCOLORS['OR'] = '000000';
$LINETXCOLORS['GR'] = 'FFFFFF';
$LINETXCOLORS['SV'] = '000000';
$LINETXCOLORS['NO'] = 'FFFFFF';
$LINETXCOLORS[''] = 'FFFFFF';

?>
